version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    target-branch: "testing"
    directory: "/"
    schedule:
      interval: "daily"
