name: Node.JS CD of testing server

on:
  push:
    branches: [ testing ]

jobs:
  build:

    runs-on: [self-hosted, testing, api, cd]

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build

  deploy:
    needs: build

    runs-on: [self-hosted, testing, api, cd]

    steps:
    - uses: actions/checkout@v2
    - run: pm2 stop ./ecosystem.config.js --only "lynix-testing-api"
    - run: npm ci
    - run: npm run build
    - run: bash ./setup.sh
      shell: bash
    - run: pm2 start ./ecosystem.config.js --only "lynix-testing-api"